### PR TITLE
Compatibility with typed properties in PHP 7.4; closes #11:

### LINKED ISSUE #11: Not compatible with typed properties in PHP 7.4
e.g. 
class MyEvent:
```
{
    use Immutable;
    public int $number;
}
```
Calling
`new MyEvent();`

will throw an Exception:
```
Typed property MyEvent::$number must not be accessed before initialization
in vendor/matthiasnoback/convenient-immutability/src/Immutable.php (line 28) 
    $this->_defaultValues[$propertyName] = $property->getValue($this);

```
Can be easily fixed by changing the line to:
```
            if ($property->isInitialized($this)) {
                $this->_defaultValues[$propertyName] = $property->getValue($this);
            }
```

### PR DESCRIPTION
**Pull request by mdi22**
Pull request fo Fix issue #11

### CODE REVIEW

File: src/Immutable.php [hunk 1]
```diff
@@ -25,7 +25,9 @@ public function __construct()
             }
 
             $this->_userDefinedProperties[$propertyName] = true;
-            $this->_defaultValues[$propertyName] = $property->getValue($this);
+            if ($property->isInitialized($this)) {
```
Comment (jdreesen) [inline src/Immutable.php]: Since `ReflectionProperty::isInitialized()` was added in `PHP 7.4` it should be as follows to not break usage in `PHP < 7.4`:

```suggestion
            if (\PHP_VERSION_ID < 70400 || $property->isInitialized($this)) {
```

Comment (mdi22) [reply src/Immutable.php]: Thank you for this hint!

**Review by jdreesen — APPROVED** [review]

**Comment by matthiasnoback** [comment]
Thanks for the PR. I'll pick this up/release it.
